version: '3.9'

services:

  weather:
    build: ./backend-apis/weather-service
    ports:
      - "5001:5001"

  traffic:
    build: ./backend-apis/traffic-service
    ports:
      - "5002:5002"

  fleet:
    build: ./backend-apis/fleet-service
    ports:
      - "5003:5003"

  ai-agent:
    build: ./ai-agent
    ports:
      - "5004:5004"
    depends_on:
      - weather
      - traffic
      - fleet
